// Import mongoose to define schemas and interact with MongoDB
const mongoose = require('mongoose');

// Define the Schema for Meeting documents
const meetingSchema = new mongoose.Schema({
  title: {
    type: String,
    required: [true, 'Meeting title is required'], // Meeting title is mandatory
    trim: true // Remove unnecessary leading/trailing whitespace
  },
  description: {
    type: String,
    default: '' // Default description is empty string
  },
  host: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User', // Reference to the User model, representing the host of the meeting
    required: true
  },
  participants: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User' // Reference to the User model, representing list of meeting participants
    }
  ],
  startTime: {
    type: Date,
    required: [true, 'Start time is required'] // Meeting must have a scheduled start date and time
  },
  endTime: {
    type: Date // Field set when meeting concludes
  },
  status: {
    type: String,
    enum: ['scheduled', 'ongoing', 'completed'], // Meeting status life cycle values
    default: 'scheduled' // Default state when meeting is created
  },
  accessType: {
    type: String,
    enum: ['public', 'restricted'],
    default: 'public'
  },
  invitedEmails: [
    {
      type: String,
      trim: true,
      lowercase: true
    }
  ],
  // AI-generated intelligence data
  summary: {
    type: String,
    default: '' // Summary of meeting discussions generated by AI
  },
  actionItems: [
    {
      text: {
        type: String // Text describing what task needs to be completed
      },
      assignedTo: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User' // Reference to user who is tasked with this action item
      },
      done: {
        type: Boolean,
        default: false // Whether the action item has been checked off
      }
    }
  ],
  // Log of chat messages exchanged during the live call session
  messages: [
    {
      sender: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User' // Reference to the user who sent the message
      },
      senderName: {
        type: String // For guest names or fallback names
      },
      text: {
        type: String // Content of the message
      },
      createdAt: {
        type: Date,
        default: Date.now // Timestamp of the chat message
      }
    }
  ]
}, {
  // Automatically add createdAt and updatedAt date fields to each document
  timestamps: true
});

// Create and export the Meeting model compiled from the meetingSchema definition
module.exports = mongoose.model('Meeting', meetingSchema);
